version: "3.9"

services:
  backend:
    build: ./server
    container_name: ridex-backend
    env_file:
      - ./server/.env
    ports:
      - "5001:5001"

  frontend:
    build: ./client
    container_name: ridex-frontend
    env_file:
      - ./client/.env
    ports:
      - "8175:8175"
    depends_on:
      - server
